# Generated by Django 2.1 on 2018-11-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, verbose_name='Denklem')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
    ]
